# Generated by Django 6.0 on 2025-12-11 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0002_alter_hotel_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name_en',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name_ru',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name_en',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name_ru',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_role_en',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_role_ru',
        ),
    ]
